# site settings
title: Ellenberger
subtitle: Brothers
site_name: Ellenberger Brothers
email: email@ellenberger.zone
description: There are five of us. It's almost too many.<br/>Students, Sofrware Engineers, Lawyers, and Educators.
baseurl: ""
url: "" # the base hostname & protocol for your site
author: Jack Ellenberger
street_address: Edina, Northfield, River Falls, and Chicago
city:
state: MN, MN, WI, and IL
# zip_code: 02134 (send it to zoom)
country: United States of America
phone: Don't call us please.

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
